export const colors = {
  homeScreenStatusBar: '#48a3c6',
  homeSearchStatusBarDarkBlue: '#007eb9',
  black: 'black',
  white: 'white',
  lightGray: 'lightgray',
  gray: 'gray',
  lightBlue: 'lightblue',
  orangeStarColor: '#e47911',
  lightGreen: 'lightgreen',
  blue: 'blue',
  red: 'red',
  addCartColor: '#EDCC69',
  buyNowColor: '#EFB167',
  priceColor: '#AB2B11',
  proceedCheckoutColor: '#FBD612',
  userInfoBackgroundColor: '#EBEBF0',
  countryPickerBtnColor: '#E7E7E9',
  activeTabBarColor: '#087F90',
  inActiveTabBarColor: '#484848',
  signInTitleColor: '#A1A1A1',
  signInBtnColors: '#FF9200',
  createAnAccountTextColor: '#7B7B7B',
};
