export const screens = {
  HOME: 'HOME',
  PRODUCTDETAILS: 'PRODUCTDETAILS',
  SHOPPINGCART: 'SHOPPINGCART',
  USERINFO: 'USERINFO',
  MENU: 'MENU',
  BOTTOMNAV: 'BOTTOMNAV',
  HOMESTACK: 'HOMESTACK',
};
export const labels = {
  fullNameText: 'Full name (First and Last name)',
  phoneNumberText: 'Phone Number',
  addressText: 'Address',
  cityText: 'City',
  stateText: 'State',
  zipCodeText: 'Zip Code',
  markAsDefaultAddress: 'Mark as default address',
  addressRequiredText: 'Street address or P.O. Box',
  addressOptionalText: 'Apt, Suite, Unit, Building (optional)',
  selectText: 'select',
  deliveryInstructionsText: 'Delivery Instructions (optional)',
  deliveryInstructionsFurtherText: 'Notes, preferences, access codes, and more',
  useAddess: 'Use this address',
  enterUserAddressInfo: 'Enter a shipping address',
  deleteText: 'Delete',
  saveLater: 'Save for later',
  totalQuantity: '1',
  conditionApplyText: 'Conditions Apply',
  clipSave: 'Save & clip save up to ',
  addGiftReceipt: 'Add a gift receipt for easy returns',
  proceedCheckout: 'Proceed to Checkout',
  price: '135.96',
  subTotal: 'Subtotal (2 items): ',
  searchBarPlaceHolder: 'Search Anything',
  delieverTo: 'Deliver to ',
  result: 'Results',
  from: 'from ',
  shipTo: 'Ships to Pakistan',
  saveText: 'Save ',
  withCoupon: 'with coupon',
  dollarSign: '$ ',
  dollarSignWithoutSpace: '$',
  importFeesText: 'No Import Fees Deposit & $9.98 Shipping to Spain',
  detailText: ' Details',
  availableText1: 'Available at a lower price from ',
  availableTextOtherSellers: 'other sellers ',
  availableText2: 'that may not offer free prime Shipping.',
  arrives: 'Arrives: ',
  countryName: 'Pakistan',
  daysRemain: 'Only 6 left in stock - order soon.',
  addToCart: 'Add to Cart',
  buyNow: 'Buy Now',
  minusSymbol: '-',
  plusSymbol: '+',
};
